- name: db configuring
  hosts: db
  become: yes
  # vars:
    # login_host: 172.31.38.29
  tasks:
  - name: install mysql server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  
  - name: start and enable mysql service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  # installing python dependencie
  - name: install python mysql dependencie
    ansible.builtin.pip:
      name:
      - PyMySQL
      - cryptography
      executable: pip 3.9
  
  # check password is already setup or not
  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: 172.31.38.29
      filter: version
    ignore_errors: yes
    register: mysql_connection_output

  - name: print output
    ansible.builtin.debug:
      msg: "{{mysql_connection_output}}"